import Foundation
struct ToonCharacter: Codable {
    let avartarUrl: String
    let name: String
    let description: String
    
    static func dummyData()-> [ToonCharacter] {
        return [ToonCharacter(avartarUrl: "https://i.pinimg.com/originals/f2/bd/10/f2bd102f9fc67e029ecd85a6ff8f8c4d.png", name: "Doreamon", description: "Doraemon là nhân vật chính hư cấu trong loạt Manga cùng tên của họa sĩ Fujiko F. Fujio. Trong truyện lấy bối cảnh ở thế kỷ 22, Doraemon là chú mèo robot của tương lai do xưởng Matsushiba — công xưởng chuyên sản xuất robot vốn dĩ nhằm mục đích chăm sóc trẻ nhỏ"),
                ToonCharacter(avartarUrl: "https://znews-photo.zadn.vn/w660/Uploaded/wyhktpu/2020_12_05/4abc.jpg", name: "Naruto", description: "Naruto là một xê-ri manga được sáng tác bởi Kishimoto Masashi. Tác phẩm kể về Uzumaki Naruto, một ninja trẻ luôn muốn tìm cách khẳng định mình để được mọi người công nhận và có ước mơ trở thành Hokage lãnh đạo làng"),
                ToonCharacter(avartarUrl: "https://genk.mediacdn.vn/2018/8/23/anh-0-1535019031645146400508.jpg", name: "Luffy", description: "Monkey D. Luffy, còn được gọi là Luffy Mũ Rơm và thường được gọi là Mũ rơm , là nhân vật chính của bộ manga và anime, One Piece . Cậu là người sáng lập và thuyền trưởng của Băng Hải tặc Mũ Rơm ngày càng khét tiếng và mạnh mẽ , đồng thời là một trong bốn chiến binh hàng đầu của băng. [25] Ước mơ cả đời của cậu là trở thành Vua hải tặc bằng cách tìm ra kho báu huyền thoại được để lại bởi Vua hải tặc quá cố, Gol D. Roger . [26] Cậu tin rằng trở thành Vua hải tặc đồng nghĩa với việc có nhiều tự do nhất trên thế giới."),
                ToonCharacter(avartarUrl: "https://chuuniotaku.com/wp-content/uploads/2020/12/tanjiro-tai-cuoc-tuyen-chon-cuoi-cung.jpg", name: "Tanjiro", description: "Kamado Tanjirou là một nhân vật hư cấu trong manga Kimetsu no Yaiba của Gotōge Koyoharu. Tanjiro là một thiếu niên thực hiện nhiệm vụ khôi phục lại nhân tính của em gái mình là Nezuko, người đã bị biến thành một con quỷ sau khi gia đình anh bị Muzan Kibutsuji giết chết."),
                ToonCharacter(avartarUrl: "https://znews-photo.zadn.vn/w660/Uploaded/oplukaa/2020_08_13/Conan_thumb.jpg", name: "Conan", description: "Conan Edogawa (江戸川 コナン Edogawa Konan?) là tên được dùng bởi Shinichi Kudo trong bộ dạng thu nhỏ. Shinichi bị thu nhỏ thành cậu bé 6,7 tuổi sau khi bị buộc uống một mẫu thuốc độc thử nghiệm gọi là APTX 4869 bởi 2 người đàn ông áo đen, sau này được biết chúng là thành viên của Tổ chức Đen.[1] Chất độc thay đổi toàn bộ cơ thể Shinichi trừ hệ thống thần kinh và vì thế Shinichi vẫn còn tính cách, trí nhớ, và khả năng trinh thám đáng kinh ngạc của bản thân. Mục tiêu của Conan là săn tìm Tổ chức Đen vì tội ác của chúng, và với hy vọng tìm được thuốc giải độc APTX 4869. Để làm được điều đó cậu có kế hoạch là làm cho thám tử vô danh Kogoro Mouri trở nên nổi tiếng với hy vọng gặp được các vụ án liên quan đến Tổ chức Đen."),
                ToonCharacter(avartarUrl: "https://static.wikia.nocookie.net/tomandjerry/images/1/14/Tom_Cat_2.png/revision/latest?cb=20200412163656", name: "Tom Cat", description: "Mèo Thomas Tom là một nhân vật hư cấu, một trong hai nhân vật chính trong loạt phim hoạt hình Tom và Jerry của Metro-Goldwyn-Mayer. Được sáng tạo bởi William Hanna và Joseph Barbera, Tom là một con mèo nhà lông ngắn, xuất hiện lần đầu tiên trong phim hoạt hình ngắn Puss Gets the Boot vào năm 1940"),
                ToonCharacter(avartarUrl: "https://i.pinimg.com/236x/f6/e5/2f/f6e52f7ea80523021ea9dfd31a267b31.jpg", name: "Phineas", description: "Phineas Flynn là 1 nhân vật nhân vật hư cấu của loạt phim hoạt hình Phineas and Ferb. Được lồng tiếng bởi Vincent Martella và thiết kế bởi Dan Povenmire. Phineas lần đầu xuất hiện cùng với các nhân vật còn lại trong tập thí điểm Rollercoaster"),
                ToonCharacter(avartarUrl: "https://cmavn.org/wp-content/uploads/2015/07/8-buoc-ve-ben-10-8.png", name: "Ben Tennyson", description: "Ben là một cậu bé 10 tuổi (15 tuổi trong Ben 10: Alien Force, 16 tuổi trong Ben 10: Ultimate Alien và Ben 10: Omniverse), thích chơi trò chơi điện tử, đi xe đạp và cũng thích gây rắc rối. Bình thường, Ben thích làm trò nghĩa hiệp nhưng cậu luôn thất bại vì yếu hơn những thằng nhóc khác. Vì tính tò mò, Ben phát hiện ra Omnitrix, giúp cậu có thể hóa thành những người ngoài hành tinh kì dị khác nhau, giúp cậu có thể bảo vệ mọi người khỏi kẻ ác và cũng dùng để quậy phá. Nhưng Ben cũng hiểu rằng việc dính vào những người ngoài hành tinh đó là hết sức nguy hiểm, hơn những gì cậu tưởng tượng, và cậu cần phải học hỏi nhiều mới có thể trưởng thành hơn. Một thông tin bên lề được tác giả tiết lộ rằng Ben có một tài khoản chơi game Sumo Slammer trực tuyến mang tên Omnitrixter"),
                ToonCharacter(avartarUrl: "https://kenh14cdn.com/thumb_w/660/2019/11/19/frozenelsa-2048x153681050075sc1-1574141347474598906717.jpg", name: "Elsa", description: "Elsa, còn được biết đến với tên gọi Nữ hoàng băng giá, là một nhân vật hư cấu xuất hiện trong bộ phim hoạt hình chiếu rạp thứ 53 của Walt Disney Animation Studios, Nữ hoàng băng giá và phần hậu truyện Nữ hoàng băng giá 2. Nhân vật được lồng tiếng chủ yếu bởi nữ diễn viên và ca sĩ Broadway Idina Menzel."),
                ToonCharacter(avartarUrl: "https://media.artoyz.net/shop/38453-large_default/dynamic-action-heroes-woody-toy-story.jpg", name: "Woody", description: "Được dịch từ tiếng Anh-Cảnh sát trưởng Woody Pride là nhân vật chính trong loạt phim Toy Story do Pixar tạo ra. Anh ta là một con búp bê giẻ rách cao bồi có dây kéo và là một trong hai thủ lĩnh của nhóm đồ chơi trong phim. Trong phim, Woody là món đồ chơi yêu quý ban đầu thuộc về một cậu bé tên là Andy Davis.")
        ]
    }
}

